### ISSUE TITLE
Checklist for ca : )

### ISSUE THREAD

**Issue by Jean-Christoffer** [AnaCascante/2023-10-15_JS2_CA_Ana-Cascante-Jean-Christoffer-Dahl_Repo#27]
Required features
The following user stories are required for a passing submission:

- [x] User with @noroff.no or @stud.noroff.no email can register profile
- [x] Registered user can login
- [x] User can view a post content feed [}
- [x] User can filter the post content feed
- [x] User can search the post content feed
- [x] User can view a post content item by ID
- [x] User can create a post content item
- [x] User can update a post content item
- [x] User can delete a post content item

Additional features since we are two  💪 

- [x] User can create a comment on a post
- [x] User can edit profile media
- [x] User can follow/unfollow a profile
- [x] User can react to a post content item

More features to take in consideration: 
- [x]  check package.json in all pages. 
- [x] #36
- [x] check script in all pages 
- [x] #35

Check that marked criteria is applied 
--- DEBUGGING AND ADVANCE JS FEATURES 
- [x] include code that is modular and split in to ES6 modules 
- [x] Destructured objects and /or arrays. 
- [x] #34
- [x] correct work of the project, without errors 

--- PEER FEEDBACK 
- [x] effective use of git branching and PRs  
- [x] effective use of planning tools 
- [x] stud can reflect on suggestions and implement feedback 
--- ALL FEATURES DELIVERED 
- [x] use of JWT to authenticate users 
- [x] user can create post 
- [x] user can update post 
- [x] user can delet post 
- [x] working search functionality
